[TASK] Port some type annotation improvements from the Core
sascha-egerer/phpstan-typo3 pull request #170
Opened 2024-08-03 16:33 UTC by oliverklee

The Core recently has received some improvements on the type annotations/declerations. Port those over to our stubs.

Also rearrage some union type to have `null` always last.

2024-08-03 16:51 UTC, oliverklee commented
I don't quite understand why PHPStan cannot resolve the type for `Repository::setDefaultOrderings()`, and I would welcome any help.

2024-08-03 16:57 UTC, oliverklee commented
Okay, I've simplified the type a bit for the time being to get this to green.

2024-08-03 17:22 UTC, sascha-egerer commented
@oliverklee I‘m on vocation but I’ll have a look end of next week

2024-08-09 14:39 UTC, sascha-egerer commented
Looks like the previous issue was due to a bug in PHPStan that is not reproducible in the PHPStan playground. Once phpstan has created it's result caches the error is gone. If i remove the result cache i get the error again. Executing phpstan once again is successful. So it is somehow a bug that does only occur if result caches are not active. I'll further investigate and create a phpstan issue once i have a minimal reproducable setup. Maybe it is also somehow related to other parts of this package - I'll investigate and come back soon.

2024-08-09 16:04 UTC, sascha-egerer commented
Ok, reason is https://github.com/phpstan/phpstan/issues/10967 and the text in the orange box: https://phpstan.org/user-guide/stub-files

> Why is PHPStan complaining about “Class not found” in a stub file?
> 
> Stub files are analysed independently from the rest of your codebase. This means that any type they’re referencing must also be present as a stub, even if you don’t want to override any of its PHPDocs.
> 
> This is a way of tackling the problem of optional dependencies. We want to report any undefined names used in the stubs to prevent typos, but at the same time we also need to support optional dependencies in PHPStan extensions. That’s why all the symbols must be defined again in the stubs, even as [empty shells](https://github.com/phpstan/phpstan-phpunit/blob/26394996368b6d033d012547d3197f4e07e23021/stubs/MockObject.stub).

2024-08-09 16:14 UTC, sascha-egerer requested changes

2024-08-09 16:14 UTC, sascha-egerer commented on stubs/QueryInterface.stub
>      /**
```suggestion
    // We have to define the constants here to be able to use them in other stubs.
    // See https://phpstan.org/user-guide/stub-files
    public const ORDER_ASCENDING = 'ASC';
    public const ORDER_DESCENDING = 'DESC';
    
    /**
```

2024-08-09 16:14 UTC, sascha-egerer commented on stubs/Repository.stub
> +     * @phpstan-param array<non-empty-string, non-empty-string> $defaultOrderings
```suggestion
     * @phpstan-param array<non-empty-string, QueryInterface::ORDER_*> $defaultOrderings
```

2024-08-09 16:15 UTC, sascha-egerer commented
@oliverklee Looks like i'm not allowed to push my changes to your fork so i just made code suggestions.

2024-08-09 16:16 UTC, sascha-egerer commented
@oliverklee Ok i was able to commit them via the GitHub interface. weird... But it should work now as expected.

2024-08-09 17:19 UTC, oliverklee commented
@sascha-egerer Looks good, thanks! 🙏

2024-08-09 18:19 UTC, sascha-egerer approved these changes

2024-08-09 18:19 UTC, merged