Allow index for ObjectStorage to be int
sascha-egerer/phpstan-typo3 pull request #48
Opened 2022-03-10 20:47 UTC by tlueder

Fixes #47

2022-03-14 10:44 UTC, sascha-egerer commented
@tlueder Thank you for your contribution! Would it be possible for you to add a test? If you don't know how just tell me. Then i'll take care.

2022-03-14 10:50 UTC, tlueder commented
I'm looking at it right now. And have no clue how to do that in this setting.

2022-03-14 11:45 UTC, sascha-egerer commented
@tlueder Just had a look at it and noticed hat `string` should not be possible at all. There is also some other special behavior in the ObjectStorage that must be implemented by a reflection like the behavior of "offsetGet".

I'll prepare a new patch for that, soon.

2022-03-14 11:54 UTC, tlueder commented
@sascha-egerer Thanks.

2022-08-09 11:59 UTC, sascha-egerer commented
Oh i totally forgot about this one... sorry. Will try to have a look soon.

2022-08-09 22:16 UTC, sabbelasichon commented
@sascha-egerer Looks good to me. In the original ObjectStorage class the methods like offsetGet have a docblock with int and TEntity specified. So i think that the string should be maybe replaced by an integer anyways for the ArrayAccess.
Have a look at: https://github.com/TYPO3/typo3/blob/main/typo3/sysext/extbase/Classes/Persistence/ObjectStorage.php#L215

2022-08-10 07:19 UTC, sascha-egerer commented
> @sascha-egerer Looks good to me. In the original ObjectStorage class the methods like offsetGet have a docblock with int and TEntity specified. So i think that the string should be replaced by an integer anyways for the ArrayAccess. Have a look at: https://github.com/TYPO3/typo3/blob/main/typo3/sysext/extbase/Classes/Persistence/ObjectStorage.php#L215

But this is not the case for TYPO3 10.4 https://github.com/TYPO3/typo3/blob/10.4/typo3/sysext/extbase/Classes/Persistence/ObjectStorage.php#L201

An then there is this behavior that returns the object itself or the information of the object depending on the param type. This is what i meant with special behavior. But there is now "conditinal return types" since PHPStan 1.6 so this can be used to write the "condition" https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types#conditional-return-types

2022-08-10 07:26 UTC, sabbelasichon commented
@sascha-egerer Thanks. But i would guess that changing string to an int in the stub will fix the problem. The stub has precedence over the original class. You would not pass a string to the offsetGet. But maybe i don´t get it completely.

2022-08-10 07:51 UTC, sascha-egerer commented
> @sascha-egerer Thanks. But i would guess that changing string to an int in the stub will fix the problem. The stub has precedence over the original class. You would not pass a string to the offsetGet, would you? But maybe i don´t get it completely.

Ok, as discussed in Slack we should do it like that. We'll change the type to be only int as this is what is allowed since TYPO3 11. Strings should not be used anymore.

The other change with the conditional return type will be implemented in a separate PR.

2022-08-13 19:55 UTC, sascha-egerer requested changes

2022-08-13 19:55 UTC, sascha-egerer commented on stubs/ObjectStorage.stub
> + * @implements \Iterator<int|string, T>
`ObjectStorage::key()`, that is the implementation for `\Iterator::key()` does return a string.
So `int` is not correct here as `Iterator` will use `int` now with this annotation. So we can't do it like that.
Internally this iterator does also use a string and not an int. So i would suggest to keep this with string and just change the annotations of the methods that have a deviating behavior

2022-08-13 19:56 UTC, sascha-egerer commented
> > @sascha-egerer Thanks. But i would guess that changing string to an int in the stub will fix the problem. The stub has precedence over the original class. You would not pass a string to the offsetGet, would you? But maybe i don´t get it completely.
> 
> Ok, as discussed in Slack we should do it like that. We'll change the type to be only int as this is what is allowed since TYPO3 11. Strings should not be used anymore.
> 
> The other change with the conditional return type will be implemented in a separate PR.
> 
> But we can still add a test for this.

Just had another look at it. I'll push a new version

2022-08-13 23:00 UTC, sascha-egerer commented
Don't know why build fails. This PR does now depend on #56 #57 and #58. So if these are merged we should check this one again.

2022-08-15 14:53 UTC, sascha-egerer approved these changes

2022-08-15 14:54 UTC, sascha-egerer commented
@sabbelasichon Could you please have a look if this looks good to you? I'll merge it if it's fine for you

2022-08-15 19:41 UTC, merged

2022-08-15 19:48 UTC, sabbelasichon commented
Looks good. Was testing it in the meantime. Thanks for merging.